sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alexward5/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true alexward5/docker-react-test npm run test
